### PR TITLE
feat/refactor(client/Crouch.lua): Block animal peds and allow for C key to be used.

### PR DESCRIPTION
**Pull request by MadsLeander**
Blocks player with animal peds from using crouch/crawl as it won't work or looks really bad.

Also blocks INPUT_LOOK_BEHIND (key: C) if the crouch key is set to the same by the player.

This should be tested more before it's merged.

### CODE REVIEW

**Comment by TayMcKenzieNZ** [comment]
Ooh! Hadn't thought about animal peds and crawling / crouching. Though I guess a IsPedHuman native should work 🤔

**Comment by MadsLeander** [comment]
I suppose yeah, seems to work fine too, not sure what is and isn't considered a "human" in GTA tho. Both u_m_y_juggernaut_01 and s_m_m_movalien_01 seem to be considered "human", which is one way odd, but at the same time, they are "humanoid" (just like the docs said the IsPedHuman native returns).

So I'll switch it over from GetPedType to IsPedHuman.

**Comment by TayMcKenzieNZ** [comment]
Alien, bigfoot and juggernauts are just human peds, I believe 🤔 but yeah, I think Rockstar mostly sets all peds as human unless of course they are indeed, an animal. I'm not too knowledgeable on natives, but I remember seeing the IsPedHuman one, so I'm merely just suggesting, but at the end of the day it's your call and whatever you believe works best ☺️

**Comment by TayMcKenzieNZ** [comment]
Tested. All working fine.

**Pull request merged**
