### PR TITLE
Small contribution

### PR DESCRIPTION
**Pull request by Mathu-lmn**

### CODE REVIEW

**Comment by iSentrie** [comment]
i made it with dot for purpose, so it be in top in folder list...

**Comment by iSentrie** [comment]
Ok, then could have changed to other symbol, but actually it doesn't matter much thought, this feature isn't used very often anyway.

**Comment by TayMcKenzieNZ** [comment]
I don't even understand why you care iSentrie, you left the team, I invited you back, you ran to other emote "creators" and talked in their ear. Why do you care soo much?

**Comment by TayMcKenzieNZ** [comment]
You say that, and yet you stalk my GitHub profile like an obsessed ex
girlfriend. You have nothing to do with the project any more, and yet
question everything Mathu and I do. If anything, you are the one creating
drama.

I kindly suggest that you move on.

**Pull request merged**
