### PR TITLE
Add check for gamebuild

### PR DESCRIPTION
**Pull request by Daudeuf**
To add a gameduild check to your animation/emote your just have to add GameBuild like GameBuild = 2699,

### CODE REVIEW

**Comment by AvaN0x** [comment]
Hey, can you merge these with the check for AdultEmotes please ? :)
https://github.com/TayMcKenzieNZ/dpemotes/blob/1de660ebb5746d3ac043bcffa0869add7b10d4b6/client/AnimationList.lua#L15364-L15379

**Comment by Scullyy** [comment]
Copy my code yet again, nice. You shouldn’t be using ~= nil either, just use `not` and stop setting entries to nil unless you plan on shifting the elements. nil doesn’t remove an entry from the table it just sets it to well…nil which will remain within the table. Anyway so glad I could be of more assistance. Merge this so myself and others know how truly helpful I have been in providing this, hands up, finger pointing etc….

**Comment by Scullyy** [comment]
You should probably also actually add the game build to each emote otherwise this is pointless too.

**Comment by Daudeuf** [comment]
Dude, we're working on the same script and you're complaining that we're going in the same direction, it's ridiculous, make sure you have the best script.

**Comment by TayMcKenzieNZ** [comment]
You're literally DMing my partners crying about them not wanting anything to do with you. Get off my GitHub and focus on your own projects. Shouldn't you be enjoying thanksgiving with your family or something? Touch Grass.

**Comment by Scullyy** [comment]
> You're literally DMing my partners crying about them not wanting anything to do with you. Get off my GitHub and focus on your own projects. Shouldn't you be enjoying thanksgiving with your family or something? Touch Grass.

Im not American, your partners have also been contacting me Lmao. People in your discord with the homies role are literally in my DMs talking trash about you. Dude go add some animations and continue to wish you could actually improve this menu.

**Comment by Scullyy** [comment]
> Dude, we're working on the same script and you're complaining that we're going in the same direction, it's ridiculous, make sure you have the best script.

I don’t care if you go about the same approach but you’re taking code directly from my menu and then this big hypocrite who uses his sexuality as a weapon is going to give you credit for my work like he already has lmfao

**Comment by TayMcKenzieNZ** [comment]
Too long didn't read. Congratulations or sorry that happened.

**Comment by Scullyy** [comment]
But anyways merge!!!! I love having my work in your menu, the same hypocrite who cries when I forked his is using code from mine without “express” permission, that is what’s so funny here.

**Comment by TayMcKenzieNZ** [comment]
Yawn

**Comment by Scullyy** [comment]
> Too long didn't read. Congratulations or sorry that happened.

Of course you read it, I bet it really offended you too

**Comment by TayMcKenzieNZ** [comment]
Resolved in https://github.com/TayMcKenzieNZ/rpemotes/pull/72.

Thanks :)

**Pull request closed without merging**
