### PR TITLE
Feat: Add Exit Emotes

### PR DESCRIPTION
**Pull request by MadsLeander**
This would add the option to add "exit emotes" that play if you cancel your current emote.

The point of adding this would be to allow for more "smooth" or "dynamic" animations to be set up, hopefully improving the "natural flow" when using emotes. Further down the line entry emotes could also be added to build on top of this.

This PR only includes getting up (getup) as an example of how it could be used, more could be added as time goes by.

I don't think I've seen any other menu with this, so it certainly should be a step ahead of other menus.

Here is a video showing it in action: https://youtu.be/uEWAz-xgHlg (sorry for the "low" fps, my pc suddenly decided to not cooperate)

### CODE REVIEW

**Comment by iSentrie** [comment]
awesome, add this to `passout1-5` too, very abusive animations

**Comment by TayMcKenzieNZ** [comment]
Oh!! I had someone else talking about exit stuff but I honestly did not understand it. I do however like this. Is it essentially playing two emotes? Like sitting, then if cancel sitting, play bla bla bla?

Thanks for the video showcase.

**Comment by AvaN0x** [comment]
Thank you for the PR!

After talking a bit with Tay on discord about this, we came up with few things:
- We would prefer a config style like the following to match the others config formats of rpemotes
```lua
ExitEmote = "getup"
ExitEmoteType = "Emotes"
```
- `ExitEmoteType` could have a default value to "Emotes" so that it's not needed by default
- Before calling `OnEmotePlay` there should be a safety check that the emote indeed exist

@TayMcKenzieNZ is not sure about where they are placed though.
Imo they have to be accessible via command but not in the menu and could be placed, maybe in a new array in `RP` as Exits (but would have to be edited to work with commands)
@TayMcKenzieNZ would prefer the emotes not being able to be played via menu or command and only via cancel emote

Up to you to think about this I think :thinking:

**Comment by TayMcKenzieNZ** [comment]
Yeah, I like the idea of EmoteMoving, EmoteLoop, AdultEmote, AnimalEmote, ExitEmote, ExitEmoteType, because even someone with very little coding or programming knowledge, will be able to understand this.

I personally don't see the point of having the exit emotes visible in the menu or accessible via the /e command, however many people may argue that that would be useful, and I think having a RP.Exits = { would be beneficial in the AnimationList.lua, and in the AnimationListCustom.lua, if people are copy pasting their Custom file, they can simply add the array into their file.

I'm just wondering how we could do like ExitEmoteType dance, shared, animal, etc, or how we differentiate all of this.

**Comment by MadsLeander** [comment]
Thanks for the input, I've done some changes to meet the requests.

There are now checks to confirm that both the exit type and emote exist. ExitEmoteType also defaults to "Emotes" if not specified.
The ExitEmote config has been changed to match the style of other configs. It is now split up into ExitEmote and ExitEmoteType.
I also added a new array in the RP table (also added in AnimationListCustom.lua) called "Exits" to allow adding exit emotes without having them appear in the menu, they are still available through commands.

**Comment by TayMcKenzieNZ** [comment]
Thank you soo much, this is perfect! :)

**Review by AvaN0x — APPROVED** [review]

**Pull request merged**
