### PR TITLE
Added new export, fix sync anim, minor performance fixes

### PR DESCRIPTION
**Pull request by TGIANN**
- Added exports["rpemotes"]:OpenEmoteMenu()
- CanPlayAnimation() added to prevent the use of animation in the air (server owners can customize this function)
- Fixed wrong translations in Turkish translation
- Minor fixes

### CODE REVIEW

**Comment by TayMcKenzieNZ** [comment]
Sorry but, why did you add an option to remove the info? I am not a fan of this. People should not be removing the credits.

**Review by Mathu-lmn — CHANGES_REQUESTED** [review]
Hello, thanks for the pr however, removing the citizen. is not useful. Also we won't merge any config option to disable the credits.

**Comment by TGIANN** [comment]
> Hello, thanks for the pr however, removing the citizen. is not useful. Also we won't merge any config option to disable the credits.

Using it without a citizen is more performance

**Comment by Mathu-lmn** [comment]
> > Hello, thanks for the pr however, removing the citizen. is not useful. Also we won't merge any config option to disable the credits.
> 
> Using it without a citizen is more performance

That is false :)

**Comment by Mathu-lmn** [comment]
see : https://github.com/citizenfx/fivem/blob/03a8b0c8f0068dd6964bdb7a195ea6a60fb47b2f/data/shared/citizen/scripting/lua/scheduler.lua#L144

**Pull request closed without merging**
