### PR TITLE
Created a method to get animation trigger strings and label strings

### PR DESCRIPTION
**Pull request by jamesmandrews**
I would like to be able to build a UI programmatically without managing a list of animations locally in my project.  I looked in the project and didn't see any exports that did what I wanted, so I created some.

The main function that will generate a table that contains the trigger string and the label string as a table, in an array, and a series of export functions that call the function passing the desired animation type.

I am not sure if this was the best file to put it in, but in my mind it made sense.

### CODE REVIEW

**Comment by jamesmandrews** [comment]
Could you explain what "invalid" means?  I am fairly new to Lua so if there a better way to produce what I was trying to get I'm not against refactoring.  It did produce what I was expecting when I tested it.

**Comment by jamesmandrews** [comment]
I made a change to the way I get the list of emotes based on type, didn't know that it would work as a key like that, so it's better than it was syntactically, but still has the same output.

**Comment by jamesmandrews** [comment]
Could you at least let me know why it was rejected?  Was it the code?  Was it the result of what the code was aimed at doing?

**Comment by TayMcKenzieNZ** [comment]
Hello and thank you for your pull request.

Regrettably, I have marked this as invalid, as the approach it takes diverges from the typical expectations associated with a pull request. It appears to emphasize individual recognition rather than fostering collaborative development, a direction that might be considered unconventional.

I can comprehend the potential benefits of creating your own UI that builds upon RPEmotes, effectively creating a "backdoor access" for this purpose. Nonetheless, the pull request not only grants this access to you, but also extends it to everyone else.

While I do acknowledge that the current UI and menu might not be the most visually appealing or resource-efficient, I personally have yet to discover a UI that suits my preferences.

Ideally, I would prefer pull requests to focus on enhancing the menu itself, given that RPEmotes remains rooted in the foundation of a community-driven project, which has always been its core strength.

**Comment by jamesmandrews** [comment]
Hello,

Thank you for your explanation on the pull request rejection.   I understand your position.  Earlier this week I was reading through other emote animation managers trying to learn how they worked.  My thought was, wouldn't it be great to have a core animation manager, with no interfaces, no key binds, that would allow server communities to build their own UIs on top of.  No one is ever going to create the perfect UI for everyone. 

Let me share with you what my vision is for my perfect UI.

I have been RP-ing on NoPixel Green. It is my first FiveM server, and the emote mechanics frustrate me.  Having to remember the trigger words, and hope I don't mistype them.  Knowing I only have a few F keys that I can key bind to left me wanting.  I stream, and I own a stream deck.  However, I use it for a lot of stream related things, and didn't want to tie it up with animation triggers.  I thought having a FiveM plugin that is essentially a stream deck on screen providing 4 pages of 25-30 buttons that someone could link their favorite animations too, would solve the problem of mistyping or having to scroll a menu (be it vertically like the one rpemotes provides, or horizontally like the one on NoPixel) to find an emote.  It's not that the rpemotes menu isn't visually appealing, it looks fine visually, but for someone who wants to quick play an animation, that kind of menu doesn't provide that kind of quick access.

Anyway, again thanks for your explanation.  I'll build my emote-deck off of my fork, and consider sending it as a PR here.

**Pull request closed without merging**
