### PR TITLE
Added/Updated Emotes & Comma Cleanup,

### PR DESCRIPTION
**Pull request by geekgarage**
Added the following emotes:
Indicate Ahead
Indicate High
Indicate Low

Updated Big Dog Dump to particle effect instead of attached prop
https://medal.tv/games/gta-v/clips/KoMRWj6pSD0_7/d13377adcr81?invite=cr-MSw4MEgsMTA2MzE1MTk5LA

clean up 700+ commas in arrays that wasn't needed in AnimationList.lua

### CODE REVIEW

**Comment by TayMcKenzieNZ** [comment]
OMG that dog shitty particle effect 😂🤌 yo do you have discord, are you in the server? I'll give you contributors role

**Comment by TayMcKenzieNZ** [comment]
Could you also add it for small dogs? If you give it an animation and then put "nil" for it, the ped will just stand there and you can essentially run around and shit 😂

**Comment by geekgarage** [comment]
> OMG that dog shitty particle effect 😂🤌 yo do you have discord, are you in the server? I'll give you contributors role

I'm on your discord now :) Same name :)




> Could you also add it for small dogs? If you give it an animation and then put "nil" for it, the ped will just stand there and you can essentially run around and shit 😂

I can try :) I've been at this for a few days only, So I'm still learning, but I'm learning fast.

**Comment by TayMcKenzieNZ** [comment]
Nice, yeah you've definitely picked up quickly lol

**Pull request merged**
