### PR TITLE
Add timeout for loading functions + config to cancel previously played animation when playing a new one

### PR DESCRIPTION
**Pull request by Mathu-lmn**
I added a timeout for the loading functions to avoid the issue with menu disappearing if the model or animation was not loading
Also I made a new option in the config to cancel the currently played emote if playing a new one because I find it useful (set it to false by default to avoid getting **multiple** reports ^^

### CODE REVIEW

**Comment by AvaN0x** [comment]
I'm not sure about the change to `RequestWalking` in `Crouch.lua` because if we look at the `fxmanifest`, `client/Crouch.lua` is started way before `client/Walk.lua` so I'd keep `LoadAnimSet` as a local function.
I haven't looked much at the crouch feature, @MadsLeander would be able to give a better feedback for this one.

Otherwise thanks for the PR!

**Comment by Mathu-lmn** [comment]
Yes I see what you mean but the RequestWalking function is only triggered after user input (key pressed or command) so the other files will be loaded I guess ?

**Comment by TayMcKenzieNZ** [comment]
Probably. Without revealing too much, we are slowly working on another version of this menu, and so major fixes etc usually get ignored in this version as it's a waste of time adding anything to V1 then adding it to V2 and vice versa.

**Comment by AvaN0x** [comment]
> Yes I see what you mean but the RequestWalking function is only triggered after user input (key pressed or command) so the other files will be loaded I guess ?

Yeah it will be loaded but to keep an order to things I like to have the functions loaded before.

**Comment by Mathu-lmn** [comment]
I understand, I reverted this commit !

**Comment by AvaN0x** [comment]
Thanks!
I'll let Tay decides what to do with the PR next, as said a V2 is getting worked on so the two review about fps count are not that big of a deal.

**Comment by TayMcKenzieNZ** [comment]
hmm... looking over this again, im not sure it's really ideal to stop previous animation then play a new one, what if you are sitting and play like a, eating burger animation, or a burger then sitting animation, it won't work because you're stopping the previous one. also, a lot of animations have "Exit emotes".

**Comment by Mathu-lmn** [comment]
added the check

**Comment by TayMcKenzieNZ** [comment]
I'll have to really check this as I'm not entirely sure, but I feel like it's a double ended sword. You make some people happy, you piss off a few others. I also like to set some configs as false by default as it's a standalone script but qbcore support; for example, hands up and finger pointing and ragdoll I set to false and if you're standalone, enable them and enjoy. 

Also unfortunately not everyone wants animal emotes.

**Comment by Mathu-lmn** [comment]
Yup I agree with you on this and that's why I set it to false by default to not piss users and then they get on discord and complain. I PR'd because I found it useful for myself and it was request by some players but if you don't find it good / useful, you can close the PR I'd understand it 😄

**Comment by TayMcKenzieNZ** [comment]
No no, I'm just admittedly a Lua noob so I'd have to actually test it.
Because I do admit that it sucks that you can't do an emote, cancel it, and
do another, if an exit emote exist. It's something we've been discussing
lol 😅

**Comment by TayMcKenzieNZ** [comment]
@Mathu-lmn are you able to record a showcase result of this code implementation so I know what to look out for? Thanks 🙂

**Comment by Mathu-lmn** [comment]
https://streamable.com/pjmrmx @TayMcKenzieNZ 
I just realised an issue and pushed a fix now

**Comment by TayMcKenzieNZ** [comment]
just watched video. ahhh right, i see! Interesting! I am not sure how we could fix it so that the next requested animation would play. currently, if an emote has an exitemote assigned to it, it will play it when the animation is cancelled, however as you witnessed, it will not play bball4, unless of course this is the fix you talk of?

**Comment by Mathu-lmn** [comment]
I fixed an infinite loop issue that caused crashing but yeah I see what you mean and that would be a very good thing, I'll think about how to do it and let you know here when I get a satisfying result !

**Comment by TayMcKenzieNZ** [comment]
The reason the exit emotes exist is for a little more realism, you get up after sitting down, rather than just teleporting back to a standing up state, or, in the case of PVP abusers, there's the exit emotes after they play passout, but there is also a little delay, not too long, but long enough to discourage them from abusing emotes during pvp.

Thanks again and apologies this hasn't been accepted yet. I'm a little picky xD

**Comment by Mathu-lmn** [comment]
It's okay haha I totally understand the exit emotes and I've never seen such feature anywhere else. Also you're the owner of this resource so you have to be picky so it fits your expectations 😄

**Comment by TayMcKenzieNZ** [comment]
Thank you for understanding, I just hope it doesn't taint development lol

**Comment by Mathu-lmn** [comment]
https://streamable.com/j8mvaq
@TayMcKenzieNZ 😄

**Comment by Mathu-lmn** [comment]
or @AvaN0x if you want to take a look 😄

**Comment by TayMcKenzieNZ** [comment]
> https://streamable.com/j8mvaq @TayMcKenzieNZ 😄

Just watched this now, sorry have been busy with work and then I think I have minor RSI, or at least I hope it's RSI.

This is actually really neat, but I would have to do some thorough testing, as you have some emotes that are static and for poses due to EmoteMoving = false; a good example of this is the airport bag pose, and then the 2nd variant which allows you to move about, but, if you play say, the non moving one and then the moving one, it wouldn't understand, and instead would play the moving one, but, since you played the non moving one, its still stuck in the emotemoving = false phase...

I will have to download it and really test the heck the heck out of it before I push it publicly.

**Comment by TayMcKenzieNZ** [comment]
OK, so, tested in game, pretty cool, doesn't allow you to mix two emotes though, such as sitting with guitar

**Comment by Mathu-lmn** [comment]
Yes that was the goal of the option. Each emote is made by itself and you can't mix any. Making exceptions is gonna be hard tho ah haha

**Comment by TayMcKenzieNZ** [comment]
Fair enough

**Comment by TayMcKenzieNZ** [comment]
@Mathu-lmn Hey! So I've come back to this PR as I've been thinking of some stuff. 

Do you think you could possibly look into something for me? It's a little unrelated to this PR, but it could possibly have already been solved within this PR;

So basically, when you perform an emote with EmoteMoving set to false, and then perform an emote with EmoteMoving set to true, the 2nd emote doesn't allow you to move, because the menu lacks the ability to reset ped task or something, so it still has your ped in the EmoteMoving false state.

An example of this, is if you were to do airportbag and then airportbag2, I think it is. One emote you don't move, the other you do, and playing a moving emote after a non moving emote, it gets stuck.

I do think however, that it should be an emote option, ie ResetPed = true, because if we were to "fix" this for all emotes, you would then fall into the issue of no longer being able to mix emotes ( ie mix two dances together, or mix eating a burger with sitting).

**Comment by Mathu-lmn** [comment]
So if I understand well, atm when you play a first emote where you can't move and then play another one that allows you to move, you still can't move and you'd like the player to be able to move ?

**Comment by Mathu-lmn** [comment]
(just fixed a small props issue with my pr)

**Comment by Mathu-lmn** [comment]
But yeah it's not gonna be possible I think as you can't change the flag of an emote while it plays to allow player control if the new one does. I find it weird that the game does not updates the config flag when a new emote is played tho :/

**Comment by TayMcKenzieNZ** [comment]
Yes, basically that 🤔

**Comment by TayMcKenzieNZ** [comment]
Tested this again just recently, used the menu and searched for weed, played weed brick, then weed brick BIG, it seemed to have gotten hung up on something before finally loading and spawning the prop. it only seems to do this every now and then. also if you play a prop emote and then a secenario, the prop from the prop emote is still visible, cancelling the emote doesn't remove the prop.

**Pull request merged**
