### PR TITLE
Update Ragdoll.lua

### PR DESCRIPTION
**Pull request by iSentrie**
1. we don't need to loop ped id, it's not going to change while in ragdoll anyway
2. correct IsPedOnFoot check, before changing declarations (wont ragdoll if exiting a vehicle, etc)
3. Wait has to be 0 to prevent sync issues as much as possible
4. supposed to be 3 booleans at the end instead of integers
5. function info is never used
6. RegisterCommand requires 3 arguments

### CODE REVIEW

**Review by geekgarage — APPROVED** [review]

**Comment by TayMcKenzieNZ** [comment]
Thanks, has been added 🙏

**Comment by iSentrie** [comment]
there is merge function for that btw

**Comment by TayMcKenzieNZ** [comment]
Yes, I know, however I did it manually as I was testing and doing other things. Has been added. Thank you.

**Comment by iSentrie** [comment]
well, don't do it then, taking credits for others work, lol

**Comment by TayMcKenzieNZ** [comment]
I said thank you, and I didn't take credit for anything. I downloaded the ragdl.lua file, updated some other things, added some custom emotes, and pushed it all as one update. 

Again, I said thank you. No need to start unnecessary drama.

**Comment by AvaN0x** [comment]
@iSentrie I couldn't merge the PR because you deleted the branch, so I added you as a Co-author, I hope this is fine.
I explained to @TayMcKenzieNZ that he shouldn't add the changes like that and he understood it.

Anyway, thank you for the PR!

**Comment by TayMcKenzieNZ** [comment]
Yes, there was a misunderstanding. Apologies. Still learning etiquettes of GitHub. I hope you understand 😔

**Comment by iSentrie** [comment]
glad we could improve and learn something new today 💪

**Pull request closed without merging**
